name: Deploy Reinvoiz Landing Page to production

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify Discord pipeline started
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: Reinvoiz Frontend Pipeline started for ${{ github.event_name }} event on branch ${{ github.ref }}.

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        
      - name: Build
        env:
          VITE_API_BASE_URL: "https://api.reinvoiz.com"
          VITE_GOOGLE_CLIENT_ID: "818084075051-a4tc533c9sbhhteu0uhndonkqprplge1.apps.googleusercontent.com"
          VITE_IPDATA_API_KEY: "3ccc7af8d7b1d171dd9c271a1e1fbd0b5959dc8ff1e369250e9ff439"
          VITE_STRIPE_MODE: "production"
        run: bun run build

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::190930221916:role/github-action-role
          aws-region: ap-southeast-1

      - name: Sync to S3
        run: |
          aws s3 sync dist/ s3://app.reinvoiz.com --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E1Y6O3ZUDC7908 --paths "/*"

      - name: Notify Discord on success
        if: success()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Reinvoiz Frontend Pipeline completed successfully for ${{ github.workflow }} - ${{ github.ref_name }} deployment :white_check_mark:"
  
      - name: Notify Discord on failure
        if: failure()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Reinvoiz Frontend Pipeline failed for ${{ github.workflow }} - ${{ github.ref_name }} deployment :x:"